// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type RefreshToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	Scope     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type User struct {
	ID                 int64
	Uuid               string
	Email              string
	PasswordHash       string
	Scope              string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	SyncLastModified   int64
	UpNextModified     int64
	HistoryModified    int64
	HistoryClearedAtMs int64
	MarketingOptIn     bool
}
