// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type AttestChallenge struct {
	Challenge []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

type AttestKey struct {
	KeyID       string
	PublicKey   []byte
	Counter     int64
	Receipt     []byte
	Environment string
	Status      string
	CreatedAt   time.Time
	LastUsedAt  *time.Time
}

type Bookmark struct {
	UserID            int64
	BookmarkUuid      string
	PodcastUuid       string
	EpisodeUuid       string
	TimeSecs          int32
	Title             string
	TitleModified     int64
	CreatedAt         time.Time
	IsDeleted         bool
	IsDeletedModified int64
	ModifiedAt        int64
}

type Device struct {
	UserID             int64
	DeviceID           string
	DeviceType         int32
	TimesStartedAt     int64
	TimeSilenceRemoval int64
	TimeVariableSpeed  int64
	TimeIntroSkipping  int64
	TimeSkipping       int64
	TimeListened       int64
	UpdatedAt          time.Time
	CreatedAt          time.Time
	PushToken          string
	PushOn             bool
}

type Episode struct {
	ID           int64
	Uuid         string
	PodcastID    int64
	Guid         string
	Title        string
	AudioUrl     string
	FileType     string
	FileSize     int64
	DurationSecs int32
	PublishedAt  *time.Time
	EpisodeType  string
	Season       int32
	Number       int32
	ShowNotes    string
	ImageUrl     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Transcripts  []byte
	ChaptersUrl  string
}

type EpisodeAlias struct {
	DeviceUuid  string
	CatalogUuid string
	CreatedAt   time.Time
}

type EpisodeComment struct {
	ID               int64
	EpisodeUuid      string
	PodcastUuid      string
	EpisodeTitle     string
	PodcastTitle     string
	UserID           *int64
	ParentID         *int64
	RootID           *int64
	Text             string
	TimestampSeconds *int32
	CreatedAt        time.Time
	EditedAt         *time.Time
	RemovedAt        *time.Time
	Quote            string
	QuoteSource      int32
	QuoteSegment     int32
}

type EpisodeReaction struct {
	UserID      int64
	EpisodeUuid string
	Kind        int16
	CreatedAt   time.Time
}

type Feedback struct {
	ID                int64
	UserID            *int64
	Message           string
	Subject           string
	Inbox             string
	Logs              string
	BitdriftSessionID string
	DeviceInfo        string
	AppVersion        string
	CreatedAt         time.Time
}

type Folder struct {
	UserID           int64
	FolderUuid       string
	Name             string
	Color            int32
	SortPosition     int32
	PodcastsSortType int32
	DateAdded        *time.Time
	IsDeleted        bool
	ModifiedAt       int64
}

type History struct {
	UserID      int64
	EpisodeUuid string
	PodcastUuid string
	Title       string
	Url         string
	Published   *time.Time
	ModifiedAt  int64
}

type ModerationReport struct {
	ID             int64
	TargetUserID   int64
	ReporterUserID *int64
	Source         string
	Reason         int16
	Context        string
	State          string
	CreatedAt      time.Time
	TargetType     string
	ContentRef     string
}

type Playlist struct {
	UserID          int64
	Uuid            string
	OriginalUuid    string
	Title           string
	IsDeleted       bool
	AllPodcasts     *bool
	PodcastUuids    *string
	EpisodeUuids    *string
	AudioVideo      *int32
	NotDownloaded   *bool
	Downloaded      *bool
	Downloading     *bool
	Finished        *bool
	PartiallyPlayed *bool
	Unplayed        *bool
	Starred         *bool
	Manual          *bool
	SortPosition    *int32
	SortType        *int32
	IconID          *int32
	FilterHours     *int32
	FilterDuration  *bool
	LongerThan      *int32
	ShorterThan     *int32
	ShowArchived    *bool
	EpisodeOrder    []string
	Episodes        []byte
	ModifiedAt      int64
	CustomQuery     string
}

type Podcast struct {
	ID                     int64
	Uuid                   string
	FeedUrl                string
	Title                  string
	Author                 string
	Description            string
	ImageUrl               string
	WebsiteUrl             string
	Category               string
	Language               string
	MediaType              string
	ShowType               string
	IsExplicit             bool
	RefreshStatus          string
	RefreshError           string
	FeedEtag               string
	FeedLastModified       string
	LastRefreshAt          *time.Time
	NextRefreshAt          time.Time
	LatestEpisodeUuid      *string
	LatestEpisodePublished *time.Time
	ContentModifiedMs      int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	BackgroundColor        string
	TintForLightBg         string
	TintForDarkBg          string
	ColorsSourceImageUrl   string
}

type PodcastRating struct {
	UserID      int64
	PodcastUuid string
	Rating      int16
	ModifiedAt  time.Time
}

type PodcastReview struct {
	UserID      int64
	PodcastUuid string
	Text        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	Scope     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type SharedItem struct {
	ID               int64
	SenderUserID     int64
	RecipientUserID  int64
	EpisodeUuid      string
	PodcastUuid      string
	EpisodeTitle     string
	PodcastTitle     string
	Note             string
	TimestampSeconds int32
	CreatedAt        time.Time
	ReadAt           *time.Time
}

type SharedList struct {
	ID           int64
	Code         string
	Title        string
	Description  string
	PodcastUuids []string
	CreatedAt    time.Time
}

type SocialFollow struct {
	FollowerUserID int64
	FolloweeUserID int64
	Status         int16
	CreatedAt      time.Time
	ApprovedAt     *time.Time
}

type SocialGroup struct {
	ID           int64
	OwnerUserID  int64
	Title        string
	Description  string
	Visibility   int16
	PodcastUuid  string
	PodcastTitle string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SocialGroupMember struct {
	GroupID     int64
	UserID      int64
	Role        int16
	InvitedBy   *int64
	NotifyPosts bool
	CreatedAt   time.Time
}

type SocialGroupPost struct {
	ID           int64
	GroupID      int64
	UserID       *int64
	ParentID     *int64
	RootID       *int64
	Text         string
	EpisodeUuid  string
	PodcastUuid  string
	EpisodeTitle string
	PodcastTitle string
	ListID       int64
	ListTitle    string
	CreatedAt    time.Time
	EditedAt     *time.Time
	RemovedAt    *time.Time
}

type SocialHandle struct {
	Handle     string
	UserID     *int64
	Status     int16
	ClaimedAt  time.Time
	ReleasedAt *time.Time
}

type SocialList struct {
	ID          int64
	OwnerUserID int64
	Title       string
	Description string
	Visibility  int16
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SocialListEntry struct {
	ListID       int64
	EpisodeUuid  string
	PodcastUuid  string
	EpisodeTitle string
	PodcastTitle string
	Position     int32
	AddedBy      *int64
	AddedAt      time.Time
}

type SocialListMember struct {
	ListID    int64
	UserID    int64
	Role      int16
	CreatedAt time.Time
}

type SocialMilestone struct {
	UserID    int64
	Kind      int16
	Tier      int32
	CrossedAt time.Time
}

type SocialProfile struct {
	UserID                  int64
	Handle                  string
	DisplayName             string
	Bio                     string
	TermsVersion            int32
	AvatarVisibility        int16
	BioVisibility           int16
	FollowedShowsVisibility int16
	TopPodcastsVisibility   int16
	StatsVisibility         int16
	HistoryVisibility       int16
	PresenceVisibility      int16
	CreatedAt               time.Time
	UpdatedAt               time.Time
	RequireFollowApproval   bool
	RepliesSeenAt           time.Time
	SocialPushDisabled      int64
	HideFromDiscovery       bool
	DigestSentAt            *time.Time
	Curator                 bool
}

type SocialRelationship struct {
	UserID       int64
	TargetUserID int64
	Kind         int16
	CreatedAt    time.Time
}

type TranscriptContribution struct {
	ID                     int64
	EpisodeUuid            string
	PodcastUuid            string
	VttBlob                []byte
	FingerprintBlob        []byte
	Engine                 string
	ModelID                string
	Language               string
	Diarized               bool
	AppVersion             string
	EpisodeDurationSeconds float64
	CreatedAt              *time.Time
	ReceivedAt             time.Time
	Attribution            string
	AttributionID          string
}

type TranscriptSighting struct {
	ID            int64
	EpisodeUuid   string
	PodcastUuid   string
	TranscriptUrl string
	Format        string
	Language      string
	Attribution   string
	AttributionID string
	Status        string
	Content       []byte
	ContentType   string
	FetchedAt     *time.Time
	ReceivedAt    time.Time
}

type UpNextItem struct {
	UserID      int64
	EpisodeUuid string
	PodcastUuid string
	Title       string
	Url         string
	Published   *time.Time
	Position    int32
	AddedAt     time.Time
}

type User struct {
	ID                 int64
	Uuid               string
	Email              string
	PasswordHash       string
	Scope              string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	SyncLastModified   int64
	UpNextModified     int64
	HistoryModified    int64
	HistoryClearedAtMs int64
	MarketingOptIn     bool
}

type UserEpisode struct {
	UserID                     int64
	EpisodeUuid                string
	PodcastUuid                string
	PlayingStatus              int32
	PlayingStatusModified      int64
	PlayedUpTo                 int64
	PlayedUpToModified         int64
	Starred                    bool
	StarredModified            int64
	IsDeleted                  bool
	IsDeletedModified          int64
	Duration                   int64
	DurationModified           int64
	DeselectedChapters         string
	DeselectedChaptersModified int64
	ModifiedAt                 int64
}

type UserPodcast struct {
	UserID            int64
	PodcastUuid       string
	Subscribed        bool
	IsDeleted         bool
	AutoStartFrom     *int32
	AutoSkipLast      *int32
	EpisodesSortOrder *int32
	FolderUuid        *string
	SortPosition      *int32
	DateAdded         *time.Time
	Settings          []byte
	ModifiedAt        int64
	NotifyEnabled     bool
	SyncedTitle       string
	SyncedFeedUrl     string
}

type UserSetting struct {
	UserID     int64
	Settings   []byte
	ModifiedAt int64
}
