// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, scope, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, scope, created_at, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    int64
	TokenHash string
	Scope     string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (uuid, email, password_hash, scope)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, email, password_hash, scope, created_at, updated_at, deleted_at, sync_last_modified, up_next_modified, history_modified, history_cleared_at_ms, marketing_opt_in
`

type CreateUserParams struct {
	Uuid         string
	Email        string
	PasswordHash string
	Scope        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Uuid,
		arg.Email,
		arg.PasswordHash,
		arg.Scope,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncLastModified,
		&i.UpNextModified,
		&i.HistoryModified,
		&i.HistoryClearedAtMs,
		&i.MarketingOptIn,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, scope, created_at, expires_at, revoked_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, email, password_hash, scope, created_at, updated_at, deleted_at, sync_last_modified, up_next_modified, history_modified, history_cleared_at_ms, marketing_opt_in FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncLastModified,
		&i.UpNextModified,
		&i.HistoryModified,
		&i.HistoryClearedAtMs,
		&i.MarketingOptIn,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, email, password_hash, scope, created_at, updated_at, deleted_at, sync_last_modified, up_next_modified, history_modified, history_cleared_at_ms, marketing_opt_in FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncLastModified,
		&i.UpNextModified,
		&i.HistoryModified,
		&i.HistoryClearedAtMs,
		&i.MarketingOptIn,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, email, password_hash, scope, created_at, updated_at, deleted_at, sync_last_modified, up_next_modified, history_modified, history_cleared_at_ms, marketing_opt_in FROM users
WHERE uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUUID(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncLastModified,
		&i.UpNextModified,
		&i.HistoryModified,
		&i.HistoryClearedAtMs,
		&i.MarketingOptIn,
	)
	return i, err
}

const pingDb = `-- name: PingDb :one
SELECT 1 as Result
`

func (q *Queries) PingDb(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingDb)
	var result int32
	err := row.Scan(&result)
	return result, err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :execrows
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserEmail = `-- name: UpdateUserEmail :execrows
UPDATE users SET email = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserEmailParams struct {
	ID    int64
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
